export const RingEnums = {
  CATEGORIES: ["Wedding", "Engagement", "Eternity"],
  SUBCATEGORIES: [
    "Women's Wedding Rings",
    "Men's Wedding Rings",
    "His & Her Matching Sets",
    "Anniversary Rings"
  ],
  ETERNITY_SUBCATEGORIES: ["Full Eternity", "Half Eternity"],  
  STYLES: [
    "Vintage", 
    "Nature Inspired", 
    "Floral", 
    "Classic", 
    "Celtic", 
    "Branch",
    "Two Tone",
    "Modern",
    "Traditional",
    "Art Deco"
  ],
  TYPES: [
    "Bridal Set", 
    "Halo", 
    "Side Stone", 
    "Solitaire",
    "Three-Stone", 
    "Two-Tone",
    "Eternity",
    "Band",
    "Anniversary",
    "Promise"
  ],
  METAL_KARATS: ["14K", "18K"],
  METAL_COLORS: [
    "Rose Gold", 
    "Two Tone Gold", 
    "White Gold", 
    "Yellow Gold",
    "Platinum",
    "Palladium"
  ],
  FINISH_TYPES: ["Polished", "Matte", "Brushed", "Hammered"],
  MAIN_STONE_TYPES: ["Gemstone", "Lab Diamond", "Natural Diamond", "Moissanite"],
  SIDE_STONE_TYPES: ["Lab Diamond", "Natural Diamond", "Moissanite", "Gemstone"],
  GEMSTONE_TYPES: [
    "Emerald", "Ruby", "Sapphire", "Amethyst", "Aquamarine",
    "Topaz", "Opal", "Garnet", "Peridot", "Tanzanite"
  ],
  STONE_SHAPES: ["Princess", "Cushion", "Oval", "Radiant", "Pear", "Trillion", "Round"],
  STONE_COLORS: ["D", "E", "F", "G", "H", "I", "J"],
  STONE_CLARITIES: [
    "FL", "IF", "VVS1", "VVS2", "VS1", "VS2",
    "SI1", "SI2", "I1", "I2", "I3"
  ],
  STONE_HARDNESS_SCALE: {
    Moissanite: 9.25,
    Diamond: 10,
    Emerald: 7.5,
    Ruby: 9,
    Sapphire: 9,
    Amethyst: 7,
    Topaz: 8,
    Opal: 5.5,
    Garnet: 6.5,
    Peridot: 6.5,
    Tanzanite: 6.5
  },
  SIZES: [
    { size: 3.00, circumference: 44.2 },
    { size: 3.25, circumference: 44.8 },
    { size: 3.50, circumference: 45.5 },
    { size: 3.75, circumference: 46.1 },
    { size: 4.00, circumference: 46.8 },
    { size: 4.25, circumference: 47.4 },
    { size: 4.50, circumference: 48.0 },
    { size: 4.75, circumference: 48.7 },
    { size: 5.00, circumference: 49.3 },
    { size: 5.25, circumference: 50.0 },
    { size: 5.50, circumference: 50.6 },
    { size: 5.75, circumference: 51.2 },
    { size: 6.00, circumference: 51.8 },
    { size: 6.25, circumference: 52.5 },
    { size: 6.50, circumference: 53.1 },
    { size: 6.75, circumference: 53.8 },
    { size: 7.00, circumference: 54.4 },
    { size: 7.25, circumference: 55.1 },
    { size: 7.50, circumference: 55.7 },
    { size: 7.75, circumference: 56.3 },
    { size: 8.00, circumference: 57.0 },
    { size: 8.25, circumference: 57.6 },
    { size: 8.50, circumference: 58.3 },
    { size: 8.75, circumference: 58.9 },
    { size: 9.00, circumference: 59.5 },
    { size: 9.25, circumference: 60.2 },
    { size: 9.50, circumference: 60.8 },
    { size: 9.75, circumference: 61.4 },
    { size: 10.00, circumference: 62.1 },
    { size: 10.25, circumference: 62.7 },
    { size: 10.50, circumference: 63.4 },
    { size: 10.75, circumference: 64.0 },
    { size: 11.00, circumference: 64.6 },
    { size: 11.25, circumference: 65.3 },
    { size: 11.50, circumference: 65.9 },
    { size: 11.75, circumference: 66.6 },
    { size: 12.00, circumference: 67.2 },
    { size: 12.25, circumference: 67.8 },
    { size: 12.50, circumference: 68.5 },
    { size: 12.75, circumference: 69.1 },
    { size: 13.00, circumference: 69.7 },
    { size: 13.25, circumference: 70.4 },
    { size: 13.50, circumference: 71.0 },
    { size: 13.75, circumference: 71.7 },
    { size: 14.00, circumference: 72.3 }
  ]};